### ISSUE TITLE
BQ2.x.x Support

### ISSUE THREAD

**Issue by Funwayguy** [Drethic/QuestBook#11]
Just putting this here as a reminder that you'll need to update Quest Book to the support the new BQ2 API. You can PM me if you need help figuring out how to hook it up.

**Comment by Drethic** [comment]
Version 2.0.0-1.7.10 and 2.0.0-1.10 now support the 2.x API.  I did have to skip the main screen if there was a bookmark but if that becomes an issue we can address it together.
