### ISSUE TITLE
Quest Book is being opened twice

### ISSUE THREAD

**Issue by WesCook** [Drethic/QuestBook#14]
I recognize this bug as BetterQuestingTriggerer had this issue for a while too.

The book is opening the Better Questing GUI twice, probably due to a handedness issue.  You can tell because you need to click the Exit button in the menu twice when accessed via the book.

**Comment by Drethic** [comment]
Looks like I have the fix for it, I just need to test it against multiplayer and update the book image.  Then I can release an update for 1.10.  Should be available tomorrow afternoon.

**Comment by Drethic** [comment]
Version 2.1.0-1.10 has been released and approved.  This issued should be addressed, unless you dual wield quest books.  I will be opening a new issue to track better internal handling for that very slim edge case.
