### ISSUE TITLE
Can't claim rewards

### ISSUE THREAD

**Issue by TrySpace** [Drethic/QuestBook#20]
Not sure if this is the right repo, but trying Project Ozone 2.3.0 Without HQM, I can unlock new quests, but can't click the claim rewards button. And no, my inventory is not full.

**Comment by Drethic** [comment]
This may have been fixed with Project Ozone 2.4.0.  Please update your pack and try again.  If you still run into issues let me and the author of Project Ozone 2: Reloaded know so it can be investigated further.
