### ISSUE TITLE
quest complete spam

### ISSUE THREAD

**Issue by flamingram** [Drethic/QuestBook#23]
hi there im playing on foolcraft and one of the quests keep on spaming quest complete and wont stop please help

**Comment by Drethic** [comment]
Do you know which version of Minecraft, Better Questing, and Better Questing - Quest Book is installed?

If not, could you provide a link to the Curse page for foolcraft you are using, and some details about the quest you are using?

**Comment by Drethic** [comment]
Closing due to lack of response
