### ISSUE TITLE
Hunting quest

### ISSUE THREAD

**Issue by ghost** [Drethic/QuestBook#24]
The "18:Bloodthirsty" quest doesn't work at all. Even if I killed almost 50 zombies, it's always 0/4 and I can't make the book count them.

**Comment by Drethic** [comment]
This sounds like either a configuration error with the Mod Pack you are using, or an issue with BetterQuesting Core.  Which mod pack are you using and is it currently up to date?

**Comment by ghost** [comment]
Same answer as for issue #25 !

PS : Your mod is still cool :P

**Comment by Drethic** [comment]
Since this seems to be an issue with editor mode and not Questbook, I'm going to close this out.  If you run into any other issues let me know.
