### ISSUE TITLE
Moder Machines : Conduits

### ISSUE THREAD

**Issue by ghost** [Drethic/QuestBook#25]
I made some Binder Composite (enough to complete the quest) but I can't "Detect/Submit", and the quest does'nt detect the Binder Composite I made. Of course, I made the Conduits Binder

**Comment by Drethic** [comment]
This sounds like either a configuration error with the Mod Pack you are using, or an issue with BetterQuesting Core.  Which mod pack are you using and is it currently up to date?

**Comment by ghost** [comment]
As I remember (it was a long time ago now :') ), I was on admin/editor. So the quest didn't work well, especially the hunt quests and the craft ones. I found a way to exit editor mode and the quests made their way. So the "issue" is that we're on editor mode from the beginning, and nothing (as I saw) rember us to exit this mode.

PS : The mod is cool :)

**Comment by Drethic** [comment]
Since this seems to be an issue with editor mode and not Questbook, I'm going to close this out.  If you run into any other issues let me know.
