### ISSUE TITLE
[1.12.2] [BQ3] The Scroll Bar is broken

### ISSUE THREAD

**Issue by TheLimePixel** [Drethic/QuestBook#26]
All the information is mentioned here: https://github.com/Funwayguy/BetterQuesting/issues/319#issuecomment-372028493

**Comment by Drethic** [comment]
QuestBook 3.1.1 release and approved on Curseforge.  This may not address the source issue since that seems to be a BQ error, but should fix the bookmark reference and is ready when the old GUI is removed.
