### ISSUE TITLE
Opening an existing book on server.

### ISSUE THREAD

**Issue by Dranemra** [Drethic/QuestBook#28]
Hello, 
  We created a quest book on another server, I've copied the .xml file over to the new server, but I can't find a way to load/give said questbook to anyone. Is there a command to open existing questbook.xml files?

We want to create quests and books on our private test server, to then load on the public server once they've been debugged.

**Comment by Drethic** [comment]
For the quest book there is a config in `YourProjectName/config/betterquesting/questbook.json`.  You can enable giving each player a book when the log in the first time and it will also give it to any user that didn't have it before the config was set.

As for importing quests from a different server, an admin on the new server should be able to access the better questing commands.  If you have additional issues importing after getting the admin interface open you'll want to reach out to @Funwayguy.  He authored the main Better Question mods and would know the best way to move them between servers.

**Comment by Dranemra** [comment]
I found the questbook.cfg (there is no .json that you speak of) in the config files. It allows me to give a questbook to anyone new signing on. That's fine and dandy, that was really not hard to find. 

You didn't answer my question. 
I have an existing QuestBook. It's an .xml file under books in my config directory. I want to be able to hand players THAT book. How do I link them? There is no list of commands on how to connect an existing book to hand out.

**Comment by Funwayguy** [comment]
For starters, BQ doesn't use XML to store quest data at all. `QuestDatabase.json` is where all that is held. Secondly, the book itself has nothing to do with how the quests are stored, it's effectively just an alternate means of opening the GUI (which usually is a hotkey) and a handy utility item for players. Finally, even if you do _correctly_ copy over this file server side to the new config directory, you'd still need to run `/bq_admin default load` to update the server side database in existing worlds. If the original isn't in the config directory then it was never saved as the default and is likely in the world directory in which it was created.

Note:
- You cannot have two databases in separate books. BQ doesn't work like that.
- If you do not save your quests as the default, you will lose all of the data with the world when it's deleted
- If you're going to be moving the files around by hand, try familiarising yourself with where they are stored and which file does what
