### ISSUE TITLE
Not compatible with the latest Better Questing.

### ISSUE THREAD

**Issue by ProsperCraft** [Drethic/QuestBook#30]
![betterquestbook](https://user-images.githubusercontent.com/4427684/50403038-b3688a00-0758-11e9-8680-ff1ff84b16ec.png)

https://gist.github.com/ProsperCraft/62a228afd6c920028c4938c7d1462eba

**Comment by Drethic** [comment]
Because the latest version is an experimental beta the versioning is not caught properly by the dependency checker.  I can make a version specifically for the EXP_NET.

**Comment by ProsperCraft** [comment]
That will be great, thank you.

**Comment by Drethic** [comment]
The 3.1.EXP_NET has been approved on Curseforge.

**Comment by ghost** [comment]
@Drethic The new release build of Better questing requires that You WILL need to update your expansion to use this new release build.

**Comment by Drethic** [comment]
@TacticalUniverse I just tested BetterQuesting-3.5.281 with questbook-3.1.1-1.12 (my latest release) and it worked as expected.  Did you find an error with 3.5.281?

**Comment by ghost** [comment]
Have not tested yet just did not know if u knew that he had listed that we had to make sure are expansion of better questing was updated to work right

**Comment by Drethic** [comment]
Ah, I see the comment on the 281 build.  I verified the code I use to open the quest interface is unchanged so you should be good to go.

**Comment by Drethic** [comment]
Because I now have the EXP_NET and EXP_NET2 files deployed and have verified my expansion works as expected with the latest changes I'm going to close this but keep an eye out for further EXP_NET betas and update accordingly.
