### ISSUE TITLE
Better Questing 3 support for 1.7.10

### ISSUE THREAD

**Issue by theshadowake** [Drethic/QuestBook#31]
As Funway guy recently backported v 3 to 1.7.10, would it be possible to update the mod to work with it (I know it's an old version but would really appreciate it if it isn't too much work). Thanks.

**Comment by Drethic** [comment]
Yes, I can update the 1.7.10 version to work with BQ v3.  It may take through this weekend though.

**Comment by theshadowake** [comment]
Thanks, you are a legend :)

**Comment by theshadowake** [comment]
Hate to post again, understand if you are busy. Any news on this.

**Comment by Drethic** [comment]
I'm actively working on it now, things have been hectic on the home front so updates are slow.  If the update to Forge works I should have it out today or tomorrow.

**Comment by mitchej123** [comment]
Hey, checking in here.  We're looking to update to BQ3 on GTNH on 1.7.10 and are using this mod.  If there's anything we can do to help out please let us know.

**Comment by Dream-Master** [comment]
@Drethic any new on a 1.7.10 update for BQ3. Would be very nice.
Thanks in advance.

**Comment by Drethic** [comment]
Due to issues on the home front I still have not been able to work on this.  I know it's anticipated and I apologize.  As soon as I can I'll get the update out.  I have the code updated to work with BQ3 but it crashes when I launch.  That's why I'm going to match Forge versions with BQ3 as soon as I have time.

**Comment by Dream-Master** [comment]
ok thanks for info. Reel life things first no rush.

**Comment by Drethic** [comment]
Or I could look at the code, have an epiphany, and get it working.  I've uploaded questbook-2.1.1-1.7.10.jar to Curse and it has been approved!

**Comment by Dream-Master** [comment]
@Drethic thanks for the update. Book works well. Thanks
