### ISSUE TITLE
Issue with Custom Quest Book Texture

### ISSUE THREAD

**Issue by jelaw21** [Drethic/QuestBook#32]
Hello, I would like to use my own custom artwork for the questbook.  I am using Content Tweaker as my resource loader. In that folder I have: 
questbook -> textures -> items -> item questbook.png

And my custom texture does not show up.

**Comment by Drethic** [comment]
Which version of Minecraft and QuestBook are you using?  Also, which version of Content Tweaker are you using?  That'll give me some leads on where to start troubleshooting.

**Comment by jelaw21** [comment]
Minecraft Version: 1.12.2 (modded) forge-14.23.5.2838
Guidebook Version: Guidebook-1.12.2-2.9.2.jar
CT Version: ContentTweaker-1.12.2-4.9.1.jar

**Comment by Drethic** [comment]
Do you have the QuestBook version?  Should be something like this: questbook-3.1.1-1.12.jar.

**Comment by jelaw21** [comment]
I've also been working with the Guidebook mod author too.
Questbook-3.1.EXP_NET2-1.12.jar

**Comment by Drethic** [comment]
Ah, ok.  Are you specifically testing out the Experimental Net version of BQ3?  I thought that was rolled into the main line already.

As for the textures, I was able to get it with [Resource Loader](https://www.curseforge.com/minecraft/mc-mods/resource-loader) by making the following path in my pack: `resources\questbook\textures\items` and putting `itemquestbook.png` into the folder.  So long as your custom image is a png and renamed to `itemquestbook` it should override it.  I will try to see if I can get Content Tweaker to do it too, but haven't used it before.

**Comment by jelaw21** [comment]
This was the version that Twitch installed, I did not specifically choose
it. But in your .jar, you have the name of the texture "item questbook.png"
with a space. I will try without the space and see if it hits.

**Comment by jelaw21** [comment]
Nailed it. Thanks.

**Comment by Drethic** [comment]
Not sure why the jar added the space, here's the path to that [file](https://github.com/Drethic/QuestBook/tree/1.12/src/main/resources/assets/questbook/textures/items).

I've archived the Experimental files to help prevent that going forward.  Thanks for pointing it out.

That's great to hear!  Hope that helps with Guidbook too.

**Comment by jelaw21** [comment]
Maybe it didn't, maybe I was just blind last night and the typeset from m
to q made the gap look like a space. My bad. That's for putting up with me,
but glad I got the experimental files!.

**Comment by jelaw21** [comment]
I had to uninstall and reinstall to get the non experiemental builds.
Thanks for your help.
